Part2
NCAR/python-tutorial pull request #53
Opened 2020-12-09 00:18 UTC by jukent

.rst text for Part 2 of the tutorial (still might flesh out the end of 'using a built-in package` section to be a math tutorial.

2020-12-10 21:13 UTC, kmpaul requested changes
There are some typos.  It took a while to review, but I think I got most of them.

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +   when it is not the logarithm is assumed to be natural (base *e*). When both arguments are entered, the function returns the logarithm of :code:`x` to the given :code:`base`\,
```suggestion
   a keyword argument (just like :code:`filename` or :code:`types` in our :code:`read_data()` function) which
   means that :code:`base` does not need to be specified.  When it is not specified, the logarithm is assumed to
   be natural (base *e*). When both arguments are entered, the function returns the logarithm of :code:`x` to
   the given :code:`base`\, 
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +      x = math.e
```suggestion
      x = m.e
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +   Something new that we have done here is use the :code:`import ... as` statements. This essentially allows us to
```suggestion
   Something new that we have done here is use the \":code:`import ... as ...`\" statement. This essentially allows us to 
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +   :code:`math.e` calls up Euler's number (*e*), the base of the natural logarithm. *e* is an irrational number with infinite decimal places, often approximated as 2.718.
```suggestion
   The symbol :code:`math.e` represents Euler's number (*e*), the base of the natural logarithm. Euler's number (*e*) is an irrational number with infinite decimal places, often approximated as 2.718. 
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +   The above function :code:`math.log(x, base)` is very useful for computing logarithms in any base - but for some common bases there are separate logarithmic functions.
```suggestion
   The function :code:`math.log(x, base)` is very useful for computing logarithms in any base - but
   for some common bases there are separate logarithmic functions. 
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +
```suggestion

```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +   Do the two values differ? :code:`math.log10(x)` is considered to be more accurate than :code:`math.log(x, 10)`\.
```suggestion
   Do the two values differ? The :code:`math.log10(x)` function is considered to be more accurate than :code:`math.log(x, 10)`\.
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +   Pi is an irrational number (like *e*) that is approximately :math:`\frac{22}{7}` or 3.14159.
```suggestion
   The math symbol :math:`\pi` is an irrational number (like *e*) that is approximately :math:`\frac{22}{7}` or 3.14159. 
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +      rads_fromfunc = radians(deg)
```suggestion
      rads_fromfunc = m.radians(deg)
```

2020-12-10 21:13 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +      print(deg, m.pi, ras, rads_fromfunc)
```suggestion
      print(deg, m.pi, rads, rads_fromfunc)
```

2020-12-10 23:16 UTC, jukent commented
> There are some typos. It took a while to review, but I think I got most of them.

Thanks! There were a lot of typos - I'm sorry for that. It is a rather large document.

2020-12-11 20:27 UTC, kmpaul commented
Yeah. I understand, though. 

This could be a reason to move to a different theme. Then we could break it up into multiple pages.

2020-12-11 20:27 UTC, kmpaul commented
I'll see if I can review this today.

2020-12-11 21:30 UTC, kmpaul requested changes
A few formatting errors that are easy to fix.

2020-12-11 21:30 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +    ..
```suggestion
       .. code-block:: python
          :lineno-start: 29

          # Output comparison of data
          print_comparison('WINDCHILL', data['date'], data['time'], data['windchill'], windchill)

       ..

       or

       .. code-block:: python
          :lineno-start: 37

          # Output comparison of data
          print_comparison('HEAT INDX', data['date'], data['time'], data['heatindex'], heatindex)

       ..
```

2020-12-11 21:30 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +    ..
Missed this formatting

2020-12-11 21:30 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +And for :code:`heatindexcomp.py`\:
Missed this formatting mistake, too...

```suggestion
    And for :code:`heatindexcomp.py`\:
```

2020-12-11 21:30 UTC, kmpaul commented on source/tutorials/yourfirst.rst
> +   .. code-block:: python
Needs a blank line before the Python code block.

```suggestion

   .. code-block:: python
```

2020-12-11 21:31 UTC, kmpaul commented
Once these formatting errors are fixed, let me know.  I'll go ahead and merge the changes.  Then we should announce the addition of the new content to Xdev and have them walk through it to make sure it works and looks good to them.

2020-12-12 20:26 UTC, jukent commented
> Once these formatting errors are fixed, let me know. I'll go ahead and merge the changes. Then we should announce the addition of the new content to Xdev and have them walk through it to make sure it works and looks good to them.

Fixed! Yes it would be great to announce this and get an extra pair of eyes on the website.

2020-12-12 21:53 UTC, kmpaul approved these changes
Let's merge!

2020-12-12 21:54 UTC, merged